### ISSUE TITLE
Question export and import

### ISSUE THREAD

**Issue by germanvaleroelizondo** [gbateson/moodle-qtype_essayautograde#27]
Hi Gordon.

Using plugin version 2019-05-07 (80) in a Moodle 3.6.2+ (Build: 20190118) server,

When I export some questions and I later import these into another course n the same server, all the target phrases are missing.

What am I doing wrong?

**Comment by gbateson** [comment]
Hi German,
I looked into the XML import/export, and it appears that it was never working, correct?
I think I can fix it, but it will take a few more hours of work.

The GIFT export/import may be more successful, but that has problems too, so please wait a little longer ;-)

**Comment by germanvaleroelizondo** [comment]
No worries mate :)

**Comment by gbateson** [comment]
German, I think this is fixed now.
That is to say, the import/export of both XML files and GIFT files should be working.
I recommend using the XML format because it captures more information about the question than the GIFT format.
Please update this plugin on your Moodle site, and let me know if you now get the behavior your expect.
Thanks :-)

**Comment by germanvaleroelizondo** [comment]
I upgraded the plugin using Moodle's administration webpage to version 2019-06-05 (84) and now question export and importing via XML files into a different course worked perfectly.

Thanks a lot Gordon. Your plugin is now even more awesome :)
