### ISSUE TITLE
Response template showing HTML tags when set to "Plain text"

### ISSUE THREAD

**Issue by senaiboy** [gbateson/moodle-qtype_essayautograde#40]
When response format is set to "Plain text", the HTML tags appear in the Response Template but not in the Sample response.

![Ashampoo_Snap_25 September 2020_20h06m07s_002_](https://user-images.githubusercontent.com/26632885/94307010-de09f700-ff6b-11ea-9e91-cf50685a1a2f.png)
![Ashampoo_Snap_25 September 2020_20h06m53s_003_](https://user-images.githubusercontent.com/26632885/94307014-e06c5100-ff6b-11ea-8643-d0ae84218b08.png)

**Comment by gbateson** [comment]
Hi senaiboy,
I have modified the settings page so that changing the "Response format", for example from "HTML" to "Plain text", will make corresponding changes in the editors for "Sample response" and "Response template". Note that when switching from the "HTML" to "Plain text", all HTML tags will be lost and will not be restored if you then switch back to "HTML", but on the other hand, this is probably what you want in most cases.

Please could you upload this plugin on your Moodle site at the next convenient opoprtunity, and let me know if this improves the situation for you.

Thanks.
