### ISSUE TITLE
"Show grade calculation?" not respected

### ISSUE THREAD

**Issue by koenr** [gbateson/moodle-qtype_essayautograde#44]
Hi Gordon,
Thank you for this grade question type. One of our teachers found the following, what appears to me as a bug:

The grade calculation is always shown to students and teachers, whatever the setting is.
I tried to look at it with debugging enabled, but there are no debug messages thrown.

Below is the feedback for a student, with "Show grade calculation?" to "Yes, show to teachers only". Same result for "No":

General feedback
Je antwoord is niet juist.

Correct response
To get full marks for this question, you must satisfy the following criteria:

If "minder" is used, award 50% of the question grade.
If "omzetting" is used, award 50% of the question grade.
If "omgezet" is used, award 50% of the question grade.

**Comment by gbateson** [comment]
Hi Koenr
what you have found is the "Correct response". To hide this from view, disable the "Right answer" checkbox in the "Review options" of the Quiz's settings. If you are previewing the question from the question bank, then set the "Right answer" to "Not shown" in the "Display options" at the bottom of the Preview window.

It seems that for this plugin, the "Correct response" is only shown if the response is not correct. In other words, if the response is judged to be correct, then the "Correct response" hint will not be shown.

I will close this issue now, but if you feel it has not been addressed, please do not hesitate to reopen it.

Kind regards
Gordon

**Comment by koenr** [comment]
Thank you for your looking in to this Gordon. 
Ah, the "correct response hint". That could be it. I didn't get that. 
I'll look into the Dutch language strings to see if I can make this behavior more clear.

Kind regards
Koen

**Comment by gbateson** [comment]
Thanks Koen!
I agree that the "Correct response" heading was confusing.

Therefore, I have changed it to "Hints to improve your grade",
which is the "feedbackhints" string in this plugin's language pack.
Since the string already exists, I don't think you need to change anything ;-)

As I mentioned before, this information only appears if the "Right answer" setting is enabled,
either by checking the checkbox in the "Review options" of the Quiz's settings,
or by selecting "Right answer: Shown" in the "Display options" at the bottom of the Preview window.

Best regards,
Gordon
