### ISSUE TITLE
Error during back up - in Moodle 3.9.4

### ISSUE THREAD

**Issue by amandadoughty** [gbateson/moodle-qtype_essayautograde#45]
error/baseelementincorrectfinalorattribute

More information about this error

×Debug info:
Error code: baseelementincorrectfinalorattribute
$a contents: errorcmid
×Stack trace:
line 125 of /backup/util/structure/base_final_element.class.php: base_element_struct_exception thrown
line 333 of /backup/util/structure/backup_nested_element.class.php: call to base_final_element->find_element_by_path()
line 247 of /backup/util/structure/backup_nested_element.class.php: call to backup_nested_element->find_element()
line 67 of /question/type/essayautograde/backup/moodle2/backup_qtype_essayautograde_plugin.class.php: call to backup_nested_element->annotate_ids()
line 74 of /backup/moodle2/backup_plugin.class.php: call to backup_qtype_essayautograde_plugin->define_question_plugin_structure()
line 160 of /backup/util/plan/backup_structure_step.class.php: call to backup_plugin->define_plugin_structure()
line 2295 of /backup/moodle2/backup_stepslib.php: call to backup_structure_step->add_plugin_structure()
line 88 of /backup/util/plan/backup_structure_step.class.php: call to backup_questions_structure_step->define_structure()
line 181 of /backup/util/plan/base_task.class.php: call to backup_structure_step->execute()
line 178 of /backup/util/plan/base_plan.class.php: call to base_task->execute()
line 145 of /backup/util/plan/backup_plan.class.php: call to base_plan->execute()
line 410 of /backup/controller/backup_controller.class.php: call to backup_plan->execute()
line 136 of /backup/util/ui/backup_ui.class.php: call to backup_controller->execute_plan()
line 175 of /backup/backup.php: call to backup_ui->execute()

**Comment by gbateson** [comment]
Hi Amanda,
I think this means that the question specified a Glossary (of Common Errors) to be used but the Glossary was not restored at the same time as the question, so Moodle didn't know what to do. Does that sound plausible?

**Comment by gbateson** [comment]
Hi Amanda,
I was able to investigate this issue further and discovered the cause of the error that you reported.

It seems that you had run the backup script when the "errorcmid" field was not in the database. This most likely reason for this is that the plugin was updated version 2019-03-03 (58) but the site administrator had not run the installation script by the time you ran your backup.

Anyway, I have modified the backup script so that it can detect this situation and will skip the errorcmid field if it doesn't exist.

Please arrange for this plugin to be updated on your Moodle site at the next convenient opportunity.

Kind regards
Gordon
