### ISSUE TITLE
(HELP) What is the main source of documentation to make this plugin?

### ISSUE THREAD

**Issue by thoriqadillah** [gbateson/moodle-qtype_essayautograde#63]
Maybe some people will answer this question directly: "just read moodle documentation, it's there". I know
But, having so little experience in programming in general (I'm still uni student), and moodle plugin development in particular, moodle docs makes me a bit confused. Currently I'm working on moodle plugin for auto grading essay, just like this plugin, but with different method. But moodle dev docs gives me hard time to understand.
When I read documentation, I'm expecting multiple example codes, what is the available option of API and how to use them, etc. But in moodle docs, most of them are just plain text with so little code (at least what I found), and expect me to seek what people already made. In other word, I'm expected to reverse engineer what already made
Maybe I'm too spoiled from reading framework documentation and expecting plugin development is the same as using framework. 
Can you help me to lead me your main source of documentation to make such plugin? Like what I need to code, how to debug my current code and display it, how to test, etc. Thank you in advance

**Comment by gbateson** [comment]
Hi Thoriq,
Official documentation for question type plugins is here:
https://docs.moodle.org/dev/Question_type_plugin_how_to

However, I've never read that page. My method is to read other people's code and learn from that.

Your plugin sounds interesting. What method will you use to grade the essay automatically?

**Comment by thoriqadillah** [comment]
So you're doing reverse engineering to other people's code as well. I'm currently learning your plugin and basically copy pasting and removing the code that I might not needed. 
But the question is, how do I debug or test to see my code is working? In web development, I just run the local server and see it update automatically. 
In moodle, moodle need to recognize the plugin and then need to update the db and whatnot. But the problem is, moodle doesn't update it automatically (I think). You need to perform some action to update it, and I don't know how to

My method is using cosine similarity to compare the similarity between the answer key and student response

**Comment by gbateson** [comment]
It seems we understand "reverse engineering" differently. I understand it to mean generating some higher level program code from compiled code, or generating readable code from obfuscated code. I'm not doing either of those things. I don't need to, and neither do you, because that code is open source and written in PHP. Everything is there in plain sight ;-)

If you want help on setting up your Moodle development environment, the following page might be a good place to start:
https://docs.moodle.org/dev/Setting_up_development_environment

Once you have setup Moodle, you just put the plugin in the correct place and then login to Moodle as admin. In the case of a question type plugin, you should put the code at "DIRROOT/question/type/PLUGINNAME", where DIRROOT is the path to the Moodle scripts folder on your server, and PLUGINNAME is the name of your question type, e.g. "essayautograde".

Interestingly, the essayautograde already uses two functions available in PHP to test for similarity between two strings:
[levenshtein()](https://www.php.net/manual/en/function.levenshtein.php)
[similar_text()](https://www.php.net/manual/en/function.similar-text.php)

You can see them in use in the "is_similar_text()" method of the "qtype_essayautograde_question" class in the following file: question/type/essayautograde/question.php (around line 590)

In your questions type, what would the "answer key" look like? Could you give a sample?

**Comment by gbateson** [comment]
Maybe you already have your own code for calculating cosine similarity between two strings, but for reference, here is a page where someone has shared some useful-looking code to do just that:
https://github.com/RnDevelover/SimpleCosineSimilarityPHP/blob/master/computeCosine.php

**Comment by thoriqadillah** [comment]
yes sir, thank your. Yeah, I think what I meant on reverse engineering have different context. What I thought as reverse engineer the code is just learning the code without the documentation. 

> You can see them in use in the "[is_similar_text()](https://github.com/gbateson/moodle-qtype_essayautograde/blob/master/question.php#L560)" method of the "qtype_essayautograde_question" class in the following file: question/type/essayautograde/question.php (around line 590)

As for `is_similar_text()`, I'm aware of that, and I already copy and paste that code into my own code haha. Currently, I'm writing on `questiontype.php`and still trying to figure out what needs to code and whatnot.

> In your question type, what would the "answer key" look like? Could you give a sample?

Let's say we have a question "What is the definition of a bee?". And the teacher will provide an answer key of that question to compare to student response, "Bee is winged insects closely related to wasps and ants, known for their role in pollination and, in the case of the best-known bee species, the western honey bee, for producing honey". And then this answer key will be used for base to compare with each student response with cosine similarity. The similarity of two string will be used to help teacher to eliminate or prioritize who needs to be manually graded (because we can't really fully accept the algorithm). The problem with autograding essay question is, student may provide a response of that question with the definition of `Bee Movie`, which is actually can be close to the definition of bee itself. And I heard that cosine similarity can tackle that and will result different similarity percentage

> Maybe you already have your own code for calculating cosine similarity between two strings, but for reference, here is a page where someone has shared some useful-looking code to do just that:
https://github.com/RnDevelover/SimpleCosineSimilarityPHP/blob/master/computeCosine.php

As for the algorithm, I have already found a library called [php-nlp-tools](https://github.com/angeloskath/php-nlp-tools/). My plan is to use that library to simplify the development of my plugin

**Comment by gbateson** [comment]
I see. Looks like you are all set for code :-) Good luck with your project 👍

**Comment by thoriqadillah** [comment]
Hi sir, just want to let you know that I have finished my plugin project, [It's here](https://github.com/thoriqadillah/essaysimilarity). Your plugin was a huge help for me to finish my project. Thank you :)
And thank you as well for answering my questions before :D
Cheers!
